### ISSUE TITLE
NanoVNA v2 does not start, just blinks 

### ISSUE THREAD

**Issue by eried** [nanovna/NanoVNA-V2-firmware#18]
Hello, I bought a nanovna v2 from aliexpress and it works for a while but sometimes it just blinks white and does not start... I tried

1) 3 different USB cables: Still bad
2) Adding internal battery: Still bad
3) Connected to power bank, phone charger, computer, usb3.0 charger: Still bad
4) Updating the firmware to 20200525: Still bad

Is this a hardware problem? or it might be firmware?

**Comment by gabriel-tenma-white** [comment]
Can you post pictures of the top and bottom side of the PCB? This sounds like a known issue with the IP5305 that comes up if C712 is populated.

**Comment by eried** [comment]
Hi, thanks Gabriel:

![image](https://user-images.githubusercontent.com/1091420/85925720-ade28780-b89a-11ea-8cdb-5392777aa408.png)

![image](https://user-images.githubusercontent.com/1091420/85925731-baff7680-b89a-11ea-89c4-35b1120d03bf.png)

**Comment by gabriel-tenma-white** [comment]
Yes that's a clone ;)
If you plug it in with the power switch in the "off" position, wait a few seconds, and switch it on, it will usually boot up. The "fix" is to remove C712 (the big electrolytic cap near the 3 pushbuttons).

**Comment by eried** [comment]
Oh it was even more expensive than the one in tindie without any accessory 😭 I thought it was genuine. Sometimes happens while powered too, but I will try what you said. I opened a dispute though because in this state is not usable

**Comment by gabriel-tenma-white** [comment]
It's the "zhonghua antenna" clone, which is actually the higher end clone since they didn't skimp on materials (you can see 8 extraneous shield clips are soldered) but unfortunately they didn't figure out why C712 is left unpopulated in the official version. Adding C712 actually reduces the noise floor, but it causes bootup issues on some devices (we only found this bug after doing a big prototyping run).

**Comment by eried** [comment]
Thanks a lot. If I am able to return it I will order from tindie (if there is stock this time :) )

**Comment by eried** [comment]
I removed the c712 but it stills blinks. There is an small audible click too

**Comment by gabriel-tenma-white** [comment]
what is blinking? the display backlight? LEDs?

**Comment by gabriel-tenma-white** [comment]
are the audible clicks in sync with the blinking or are they independent?

**Comment by eried** [comment]
Independent. I think there might be some soldering problems, if I press some of the chips the blinking stops but then the screen is all white. Any idea when the one with 4 inches screen will be available in your page?

**Comment by gabriel-tenma-white** [comment]
the LCD backlight blinks?

**Comment by eried** [comment]
Yes, and a led in the back. But if I press or move stuff (I'm not sure what) the screen is steady white. Worked for a few instants yesterday but it was very noisy:
![IMG_20200627_212053](https://user-images.githubusercontent.com/1091420/85945322-4f221a00-b93d-11ea-857a-3344de4351e3.jpg)

And this is how it blinks sometimes
https://photos.app.goo.gl/2DqjpHAdbBLuVP6f9

**Comment by gabriel-tenma-white** [comment]
Still looks like a IP5305 issue or excessive current draw, you can try bridging the + terminal of C711 (the other electrolytic) to the + terminal of C712 to bypass the IP5305. Check if anything on the board is getting hot.

The traces look like one or both of the ADF4350 are broken (you can tell that it's normal up to 140MHz and then completely random above that). All the ADF4350s sold in China under $1 are salvaged ones. PM me and I'll give you more info (OwOwOwOwO123@outlook.com or スメグマ#2236 on discord).

**Comment by gusosborne** [comment]
I just have to chime in here to say.. I really appreciate your willingness to help support the community here (as well as on groups.IO), even when it's an obvious clone. Very Cool, very nice of you.:)
Thank you!

**Comment by douardda** [comment]
Shouldn't this issue be closed now?

**Comment by douardda** [comment]
@eried @gabriel-tenma-white could one of you close this issue now? Thanks

**Comment by eried** [comment]
just for the record: I bought a genuine one and no issues :)

**Comment by wojciechna** [comment]
Hi
I would like to refresh topick.
 I have the same Nanovna V2.2 colne and similar problem. When i bought it after turn it on display stayed white and noticed that if I pluged cabble in when swith was off, whaited couple seconds than turrn it on and vna started normaly. That was before I updated firmware version to _nanovna-v2-20201013-v2_2_8_ in the way described here: https://nanorfe.com/nanovna-versions.html .But on Macbook. I couldn't do this on Windows due to the _NanoVNA-QT_ was turning off after opening firmware BIN file. Old firmware was from 2020 May I think made by edy555. Now Nanovna screen stay white all the time. I can still use it but only on PC with _NanoVNA-QT_. I tried disconect and connect batery but it didn,t help. My PCB doesn't contain C712 described above(even slots on PCB for this CAP are empty). I thout meybe it would help to do clearconfig via PuTTY but I dont get any respond in PuTTY terminal, propably I do something wrong(here I've found that you can do clearconfig: http://tatek.home.pl/j3/images/warsztat/elek/nanovna02/NanoVNAUpg_17.jpg). Anny ideas what can help ? I was thinking abut bridging C711 to C712 described above but just woried about to do not burn anything :). I would aprishiate anny help. Thanks

![image](https://user-images.githubusercontent.com/81753402/167952301-2ac35e30-48d1-4082-81c6-7ade116155e9.png)

**Comment by ghost** [comment]
Hi
just for informations i had the same problem with the cable from my printer ...it's mistake my screen blinks.
i take the original cable from my nanovna2...no problem ...it's just a test.
![409803031_235935286196642_3851123356660272080_n](https://github.com/nanovna-v2/NanoVNA2-firmware/assets/154803382/321c18dd-404b-4a79-a02b-44d808aa5e8a)
