### ISSUE TITLE
Unable to enter DFU mode

### ISSUE THREAD

**Issue by nieldk** [nanovna/NanoVNA-V2-firmware#7]
After updating to the recent firmare - git-20200531-429c186 I am unable to stay in DFU mode.

menu->config->dfu->reset and enter dfu 

It does enter DFU, but the device resets instantly and powers up in normal mode.

**Comment by nanovna** [comment]
does entering dfu by holding down the left button still work?

**Comment by nieldk** [comment]
No, it also boots straight up (everything seems to work as normal, just I can’t enter DFU)

**Comment by nlroth** [comment]
That was never an option on the original Nanovna.On the H4, you could enter DFU by pushing the jog straight in and applying power.It's a hardware thing - not software.Anyone can modify their older nanovna device by adding a jumper and changing a resistor so that it too, can enter DFU by holding in the jog switch and applying power.See my post on that (Search through my posts from the last 6 months - can't remember the number off hand)
Regards,Larry

    On Tuesday, June 2, 2020, 8:42:47 a.m. EDT, nanovna <notifications@github.com> wrote:  
 
 


does entering dfu by holding down the left button still work?

**Comment by nanovna** [comment]
if you used st-link or jtag programmer to flash the firmware, it probably overwrote the bootloader at 0x08000000, you can reflash the bootloader at 0x08000000 and firmware at 0x08004000. if you used dfu to flash the firmware it protects against writing to the bootloader.

**Comment by nieldk** [comment]
This is the Nanovna-2 firmware Rev 2.02 board, not the original version 1.

I figured out the problem. I flashed the bootloader, and now it works again.
Probably I erased that when flashing using Jlink.

**Comment by nieldk** [comment]
Solved by flashing bootloader
